rest:
  - authentication: none
    scan_interval: 30
    resource: http://192.168.2.154/farm-info
    sensor:
      - name: "homefarm"
        json_attributes:
          - "humidity"
          - "temperature"

template:
  - sensor:
      - name: "Luftfeuchtigkeit"
        unit_of_measurement: "W"
        device_class: "power"
        state_class: "measurement"
        unique_id: "homefarm_humidity"
        state: >
            {{ state_attr('sensor.homefarm', 'humidity') }}
      - name: "Energie_Bezug"
        unit_of_measurement: "kWh"
        device_class: "energy"
        state_class: "total_increasing"
        unique_id: "energy_received"
        state: >
            {{ state_attr('sensor.poweropti', 'A_Plus') }}
      - name: "Energie_Einspeisung"
        unit_of_measurement: "kWh"
        device_class: "energy"
        state_class: "total_increasing"
        unique_id: "energy_fed"
        state: >
            {{ state_attr('sensor.poweropti', 'A_Minus') }}
            
            
