#
# UrbanHive REST API
#
rest:
  - authentication: none
    scan_interval: 30
    resource: http://192.168.2.154/farm-info
    sensor:
      - name: "homefarm"
        json_attributes:
          - "humidity"
          - "temperature"

template:
  - sensor:
      - name: "Luftfeuchtigkeit"
        unit_of_measurement: "%"
        device_class: "humidity"
        state_class: "measurement"
        unique_id: "homefarm_humidity"
        state: >
            {{ state_attr('sensor.homefarm', 'humidity') }}
      - name: "Temperatur"
        unit_of_measurement: "°C"
        device_class: "temperature"
        state_class: "measurement"
        unique_id: "homefarm_temperature"
        state: >
            {{ state_attr('sensor.homefarm', 'temperature') }}
